### PR TITLE
Fix several audit issues

### PR DESCRIPTION
**Pull request by cf-sewe**
# Pull request details

**Overall Review of Changes:**

Mostly, fixed some false alarms.

**Issue Fixes:**
n/a

**Enhancements:**
n/a

**How has this been tested?:**
Executed run_audit.sh and checked the results.

### CODE REVIEW

**Comment by uk-bolly** [comment]
hi @cf-sewe 

Superb work, as mentioned the new run_audit script is now merged, so i am hoping all is good to go once you pull that in. I will test further tomorrow.
Brilliant effort

thanks

uk-bolly

**Comment by cf-sewe** [comment]
Thank you for your prompt response and warm words! 
Merge from remote:devel is done now. 

(I decided not to merge the spacing/formatting changes for now and focus on functional topics first)

**Comment by cf-sewe** [comment]
FYI I tested with latest goss version 0.4.x and it generally works. Some deprecation warnings but nothing functional I would say.

**Comment by uk-bolly** [comment]
> FYI I tested with latest goss version 0.4.x and it generally works. Some deprecation warnings but nothing functional I would say.

Thats the next thing i'm working on around audit, when not on client work. 0.4 has some great changes and gets around a few limitations ive hit so i'm rewriting to utilise that more, hence the check on goss version now in the script :).
If i can get a yamllint working with this format that would help so much with the lint.

Thanks again

uk-bolly

**Review by uk-bolly — APPROVED** [review]
superb changes

**Pull request merged**
